language: scala

cache:
  - directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

# See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
# Tricks to avoid unnecessary cache updates
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

# based on https://github.com/jruby/jruby/blob/master/.travis.yml
before_install:
  - unset _JAVA_OPTIONS
  - export JAVA_OPTS="$JAVA_OPTS -Xms512m -Xmx2048m"

install:
  - npm install jsdom@12.2.0

before_script:
  - unset _JAVA_OPTIONS # travis/travis#8408
  - echo $HOME
  - echo $JAVA_OPTS

jdk:
  - oraclejdk8

jobs:
  include:

    - stage: test
      scala: 2.11.12
      script: sbt "wow $TRAVIS_SCALA_VERSION" test manual/makeSite
    - stage: test
      scala: 2.12.8
      script: sbt "wow $TRAVIS_SCALA_VERSION" test
    - stage: test
      scala: 2.13.0-M5
      # requires strict aggregation because 2.13 is not supported by all the modules
      script: sbt "+++$TRAVIS_SCALA_VERSION test"

    - stage: coverage
      script:
        - sbt "wow 2.11.12" coverage test coverageReport coverageAggregate
        - bash <(curl -s https://codecov.io/bash)

    - stage: publish
      if: tag =~ ^v
      script:
        - openssl aes-256-cbc -K $encrypted_6d2e0e4487f6_key -iv $encrypted_6d2e0e4487f6_iv -in ci/secrets.tar.enc -out ci/secrets.tar -d
        - tar xvf ci/secrets.tar
        - chmod 600 ci/travis-key
        - eval "$(ssh-agent -s)"
        - ssh-add ci/travis-key
        - sbt "wow 2.11.12" manual/makeSite +publishSigned sonatypeRelease manual/ghpagesPushSite

env:
  global:
    # SONATYPE_USERNAME
    - secure: "KI0QBOV/suiS6sVSI9+TYeASxCCyvJQx1Bot3UoOfOMna9ZycDf/wDxPSEuy3XlgK+fcLUMXbTyjrdt/rb0lMLBtzRWScvEEG6sp0yL0TbKvwYRNaVWXOGzRePeJ9bgHIInpKptuyK7GgWU3Mj9T+LUVSZiVdarWbLILe1TBV0gJbsG3YE2ODDBLqlBE0NmMf0a0UX/ASbgIQSmZ+wd9l8UcjXv5bpY9Tv5LzsfOJlWIY1xHucMd6rgE62h2d9MYQCXTj349i1QOBtiVufBKyWRJgYedvh3H+cNOHxyM0eyxcp/yX/NbtoD4JHmE4LM51MStsmobZ71Be/bnse9G2DueOKKFJJ1wiJswbjJsnbJTbqLn2zykrtj6bhFhVvJ3UJ9Z+gZQMKSJbrxfYRv0Brw/a+qDUR2KsIFF2H/vwtfqr7Es8FfBlrkpQ/0GMHPxv+ahjI4m/YBzWqnBBfSUTbRDE61/Z/ST/A4T1EMLws+kYcrR7mLN0+M/vnLb21SsZsatKdxYQEu6iBD7Q4UIhNl9W9DrUm2iQRuc4AIpazKvUttw8+yhEviKBbnylTzQlK5lEKSjxW8qPzH7P+ojam2MdZi88vtsXzICXzmRkRMo/d31f7K3DCp0mU8Q6eE1L03xnCJEhZ1gSDG4RtetU4S9nC36PxBGAtNyQjP+5yA="
    # SONATYPE_PASSWORD
    - secure: "iwQQIRHAoy91n1JIx8HvJSyaJlsERoWUI4gJWrDDxqwVXSpIykQtOc9lOvC751VuwpFVV8jT9RliMmrZ2gP1PGWQj2HGzKpG0+ZzbClG5z1bwc2Y6MN2Ua5pDofhtY4q6BthwggBE0AOd3sM+QIbY9hF/lFf0juYWmxaCR3sAA7+D/xXS3W8JX8sElqbsB+VtdbZOs6jg9C9dMzR2P1f4/LN3wJvtHqGUrmLd/5z/QF+fz95bHZS/ve7cqEzTOnf5uzA7/so3ne3iRtYXibCSpU3/UAh57rklJIITS/eLnNIxVNTHWHFTe6fdZQjHvhEb3qNzs5/3uHWYlfqQQ/MTR9q0KKQA8jB7Omtq8+1w6BZQE+gQw2fOv9iELthrAHUSWEJ8BH2oTGG65IbTXO702RnvwRHtCd+jXPIA1FVx6956loUnvvzybVvke0VxU7u3w5UmJObM6iidn0C3rAidpFxwmpY76vsQtl0F5RfCPj3tKSFQwip7259ZRrdlxvSpo6SfVZkNjBzT2cBf9AmV+5ls/aWx2AEOL/j61bQR4gbbcXv9C9+NyCrpg3Gf2RrTzO1EvgSSAEt2KMthOlcHs85zttBNyFjXlLAYPGeZuI9FAtT/3wc7WARQczhjF1tBcUiYnzqa1OER/8ZbGzegz5gej2vTOByfcYEGn3D39w="
    # PGP_PASSPHRASE
    - secure: "PkqB6lk8ZjsSH4gUSKxOD/OAzwA3ZI0uwsl90y9rE6amcT4+ojzQcjl05KdU/KsvjtSuwqsW3Gkkq9tY0gCYWHtc8N956lk8zTeW0Pn17q4sn/8FHwP7ll9owpvhAYGFpQOEFDSK9IgHlzaAn9EcFb5YWxzfT3ZKGmyTChjQvMws1aJdgocF15rG73Dj+g8BjfhSG/csxRZegwD4cef48bW7q0uIR3tJ84aOPGu1ibkSAYToxg7Wjr5ENf+K3SZ8JAyoh4/8RcBQw7bknxTiPcvavwufyOINQlW0KeKww13EypsOpjPYfFwdqdsc5xh+Xp06awp8X92ae4K2bHs2MdWm4pzjYDPX+LKhBNnDpbRDJ/6cMqOoFzUdBNlTNQsEfHvnlBSMMEHCkgxp9FhQGsjF0q8FmyAxJ301jRcBcoeseM1qPcFFVLXOtaeiwwK+o5FKso6IEyAxzL2aNTTiO9OYQWLWMfwNAGye+dl7Egc7galfTuVLDJWgID38eezKjsxDNpe1IGjqXD+tM7k7de2iEf9nyqY7hPg8ar0dLgobE23mcxuhMJ5LMe7DJ4MyNM9yIBYEl7TsBUqS1g2H6O4daIrYdqFzkL42OFEp/AzugsfmNs6BtiCAs52gfwgi+u6iSuiS9buAfq5gcPLrmW8oUYXEGfWiNHQHpmfbmKI="
